# Generated by Django 4.2.11 on 2024-03-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorADC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('tournament', models.CharField(max_length=240, verbose_name='Tournament')),
                ('matchId', models.CharField(max_length=240, verbose_name='MatchId')),
                ('summonnerName', models.CharField(max_length=240, verbose_name='SummonnerName')),
                ('seriesId', models.IntegerField(verbose_name='SeriesId')),
                ('xpd15', models.IntegerField(verbose_name='XPD@15')),
                ('gd15', models.IntegerField(verbose_name='GD@15')),
                ('csMin', models.FloatField(verbose_name='CS/Min')),
                ('kills', models.IntegerField(verbose_name='Kills')),
                ('deaths', models.IntegerField(verbose_name='Deaths')),
                ('assists', models.IntegerField(verbose_name='Assists')),
                ('kp', models.FloatField(verbose_name='KP%')),
                ('dpm', models.FloatField(verbose_name='Damage/Min')),
                ('jungleProximity', models.FloatField(verbose_name='JungleProximity')),
                ('botLanePresence', models.FloatField(verbose_name='botLanePresence')),
                ('riverBotPresence', models.FloatField(verbose_name='riverBotPresence')),
            ],
        ),
    ]
