# Generated by Django 4.2.11 on 2024-03-23 15:58

from django.db import migrations
import csv

class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0001_initial'),
    ]

    operations = [
    ]
