# Generated by Django 4.2.11 on 2024-03-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavioradc',
            name='patch',
            field=models.CharField(default=14.5, max_length=240, verbose_name='Patch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='behavioradc',
            name='date',
            field=models.CharField(max_length=240, verbose_name='Date'),
        ),
    ]
