# Generated by Django 4.2.11 on 2024-03-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0002_behaviorADC'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavioradc',
            name='date',
            field=models.CharField(max_length=240, verbose_name='Date'),
        ),
    ]
